name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - name: Prepare git
        env:
          GITHUB_USER: 1gtm
          GITHUB_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
        run: |
          env | sort | grep GIT
          git config --global user.name "${GITHUB_USER}"
          git config --global user.email "${GITHUB_USER}@appscode.com"
          echo "https://${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
          git remote set-url origin https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git remote -v

      - name: Push
        run: |
          git fetch origin
          git checkout master
          touch xyz.txt
          date >> xyz.txt
          git add .
          git commit -a -s -m 'add all'
          git push origin HEAD -f
